#!/bin/bash
 
INTERVAL="1"  # update interval in seconds
 
if [ -z "$1" ]; then
        echo
        echo usage: $0 [network-interface]
        echo
        echo e.g. $0 eth0
        echo
        exit
fi
 
IF=$1
 
while true
do
        R1=`cat /sys/class/net/$1/statistics/rx_bytes`
        T1=`cat /sys/class/net/$1/statistics/tx_bytes`
        sleep $INTERVAL
        R2=`cat /sys/class/net/$1/statistics/rx_bytes`
        T2=`cat /sys/class/net/$1/statistics/tx_bytes`
        if [ ! -z "$R1" ]; then
          TBPS=`expr $T2 - $T1`
          RBPS=`expr $R2 - $R1`
          TMBPS=$(( (8 * $TBPS) / 10**6 ))
          RMBPS=$(( (8 * $RBPS) / 10**6 ))
        fi
        echo "TX $1: $TMBPS mb/s RX $1: $RMBPS mB/s"

done